"""r3LAY MCP server — exposes the bridge as schema-typed tools.

Runs as a stdio subprocess spawned by Hermes (see
`hermes-profile/config.template.yaml :: mcp_servers.r3lay`). Lives on the
HOST, not inside the Docker sandbox, so it can hit localhost:8765 directly —
no container boundary, no host.docker.internal magic, no shell escaping, no
curl, no URL/port hallucination.

Architecture rationale: SKILL.md + terminal + curl loses against the LLM's
statistical prior for "what a REST API looks like" — the agent invents ports,
endpoints, and drops auth headers. MCP tools are schema-typed, not advisory
prose, so the hallucination surface goes away entirely.

The tool schemas ARE the contract. Each tool has typed parameters and a
docstring the agent reads as part of its tool list, and the MCP runtime
enforces the schema before the call reaches the bridge.
"""

from __future__ import annotations

import logging
import os
import sys
from pathlib import Path
from typing import Any

import httpx
from mcp.server.fastmcp import FastMCP

logger = logging.getLogger("r3lay.mcp")

# ─────────────────────────────────────────────────────────────────────────────
# Bridge client
# ─────────────────────────────────────────────────────────────────────────────
# The MCP server runs on the HOST (Hermes spawns it as a stdio subprocess via
# the `mcp_servers.r3lay` config block). No container boundary to cross, so
# the bridge is reachable at plain localhost. Override via R3LAY_BRIDGE_URL if
# the bridge lives elsewhere.
#
# Auth: same precedence as the r3 CLI wrapper —
#   1. R3LAY_API_KEY env var (if set)
#   2. ~/.r3lay/api-secret file (auto-generated by the bridge on first run)
# Missing/unreadable key → all tool calls will return 401 from the bridge.

BRIDGE_URL = os.environ.get("R3LAY_BRIDGE_URL", "http://localhost:8765").rstrip("/")
_SECRET_PATH = Path.home() / ".r3lay" / "api-secret"
_REQUEST_TIMEOUT = float(os.environ.get("R3LAY_MCP_TIMEOUT", "300"))


def _load_api_key() -> str:
    """Resolve the bridge API key. Returns empty string if unavailable."""
    env_key = os.environ.get("R3LAY_API_KEY", "").strip()
    if env_key:
        return env_key
    try:
        if _SECRET_PATH.exists():
            return _SECRET_PATH.read_text().strip()
    except OSError as e:
        logger.error("Failed to read %s: %s", _SECRET_PATH, e)
    return ""


# Module-level async client. Lazy-initialized so (a) tests can inject a
# MockTransport before the first call, and (b) the API key is read at
# first-call time, not at import time — if the bridge starts AFTER the
# MCP subprocess and generates ~/.r3lay/api-secret on first run, we'll
# still pick it up.
_client: httpx.AsyncClient | None = None


def _get_client() -> httpx.AsyncClient:
    """Lazy-init the shared httpx client."""
    global _client
    if _client is None:
        api_key = _load_api_key()
        _client = httpx.AsyncClient(
            base_url=BRIDGE_URL,
            headers={
                "X-R3LAY-Key": api_key,
                "Content-Type": "application/json",
            },
            timeout=_REQUEST_TIMEOUT,
        )
    return _client


async def _get(path: str) -> Any:
    """GET a bridge endpoint, raising on non-2xx."""
    response = await _get_client().get(path)
    response.raise_for_status()
    return response.json()


async def _post(path: str, body: dict[str, Any]) -> Any:
    """POST JSON to a bridge endpoint, raising on non-2xx."""
    response = await _get_client().post(path, json=body)
    response.raise_for_status()
    return response.json()


async def _delete(path: str) -> Any:
    """DELETE a bridge endpoint, raising on non-2xx."""
    response = await _get_client().delete(path)
    response.raise_for_status()
    return response.json()


# ─────────────────────────────────────────────────────────────────────────────
# MCP server — FastMCP wrapper
# ─────────────────────────────────────────────────────────────────────────────
#
# Tool naming: FastMCP uses the Python function name as the MCP tool name.
# Hermes prefixes them at registration time as `mcp_r3lay_<tool>` so they
# don't collide with built-in tools (see Hermes's MCP docs).
#
# Docstrings are part of the schema — the agent sees the first line as the
# summary and the body as the description. Be explicit about MUTATING vs
# read-only behavior and when to confirm with the user.

mcp = FastMCP("r3lay")


@mcp.tool()
async def track_path(
    path: str,
    auto_index: bool = True,
    notes: str = "",
) -> dict[str, Any]:
    """Register an external folder for r3LAY to index and track.

    Use this for paths OUTSIDE the r3LAY workspace (~/r3LAY/) that you want
    the project brain to reference — the knowledge vault at
    ~/Documents/knowledge_vault, an archived repo in ~/Documents/Programming,
    or any other tree that lives under one of the configured allowed roots
    (see tracked_path_allowed_roots in r3lay-config.yaml).

    Projects that already live inside ~/r3LAY/programming/ are auto-indexed
    by the file watcher and do NOT need tracking — this tool is the escape
    hatch for folders that can't move into the workspace.

    MUTATING. Always confirm with the user before calling:
    inserts a row into tracked_paths AND (by default) runs the initial index
    synchronously.

    Args:
        path: Absolute host path to the folder. Tilde expansion is handled
            server-side. The bridge rejects symlinks and any path that
            doesn't resolve under an allowed root.
        auto_index: If True (default) run the indexer immediately. Set False
            to track metadata now and defer indexing to a later
            reindex_path() call.
        notes: Optional free-text description stored alongside the row.

    Returns:
        {id, path, is_git_repo, git_remote, git_local_head, indexed,
         files?, chunks?, project_id?}

        If auto_index was True and indexing failed, the tracked_paths row is
        rolled back by the bridge and the response carries
        {indexed: False, index_error: "...", index_status: "failed"}.
    """
    body: dict[str, Any] = {"path": path, "auto_index": auto_index}
    if notes:
        body["notes"] = notes
    return await _post("/tracked", body)


@mcp.tool()
async def untrack_path(tracked_id: str) -> dict[str, Any]:
    """Stop tracking an external folder. Indexed content stays in the DB.

    Removes the row from tracked_paths but does NOT delete the indexed
    chunks, embeddings, or project record. Untracking is metadata-only —
    reversible by calling track_path again.

    If the user wants to fully purge indexed content, point them at the
    project deletion flow. Don't do it implicitly here.

    Args:
        tracked_id: The 16-char id returned by list_tracked() or track_path().

    Returns:
        {"status": "untracked", "path": "<original path>"}
    """
    return await _delete(f"/tracked/{tracked_id}")


@mcp.tool()
async def list_tracked() -> list[dict[str, Any]]:
    """List all tracked external paths with staleness info.

    Read-only. Safe to call whenever you want to surface staleness to the
    user WITHOUT initiating a reindex on your own authority. Each row
    carries:

      - id, path, notes, is_git_repo, git_remote, project_id, last_indexed_at
      - git_local_drift: True if the local HEAD moved since last record
      - git_current_head: current local HEAD SHA (None if not a git repo)
      - fs_newer_than_index: True if any file under the path has mtime
        newer than the last index run (filesystem vs index staleness)

    If you surface staleness to the user, STATE the fact and stop. Do not
    offer to reindex unless the user explicitly asks.
    """
    return await _get("/tracked")


@mcp.tool()
async def reindex_path(tracked_id: str) -> dict[str, Any]:
    """Re-run the indexer on a tracked path. USER-INITIATED ONLY.

    MUTATING. Replaces existing vectors with fresh embeddings. Expensive.
    DO NOT call based on your own judgment. Only call when:

      1. The user explicitly asked ("reindex X", "update the index for X")
      2. A scheduled/cron job invoked it out-of-band

    Surfacing staleness via list_tracked() is INFORMATION, not
    authorization. The user may be intentionally holding off until they're
    done editing.

    Args:
        tracked_id: The id of the tracked path to reindex.

    Returns:
        {id, path, files, chunks, project_id}
    """
    return await _post("/reindex", {"tracked_id": tracked_id})


@mcp.tool()
async def git_check(tracked_id: str) -> dict[str, Any]:
    """Fetch upstream state for a tracked git repo. READ-ONLY.

    Runs `git fetch --quiet` inside the tracked repo (NO merge, NO pull)
    and computes how many commits local is behind/ahead of upstream.
    Updates git_remote_head and last_git_check_at on the tracked row.

    Safe to call freely — no working-tree mutation.

    Args:
        tracked_id: The id of a tracked path where is_git_repo is True.

    Returns:
        {id, path, local_head, upstream_head, behind, ahead, in_sync}
    """
    return await _post("/git/check", {"tracked_id": tracked_id})


@mcp.tool()
async def git_pull(tracked_id: str) -> dict[str, Any]:
    """Fast-forward pull a tracked git repo, then re-index it.

    MUTATING. Always confirm with the user before calling. NEVER call based
    on your own judgment — "there are upstream commits" is INFORMATION, not
    authorization.

    Uses `git pull --ff-only` — fails on diverged branches and dirty
    working trees (the bridge surfaces the failure as a 502). Does NOT
    rebase, does NOT force, does NOT push.

    Args:
        tracked_id: The id of a tracked path where is_git_repo is True.

    Returns:
        {id, path, git_output, new_head, files, chunks}
    """
    return await _post("/git/pull", {"tracked_id": tracked_id})


@mcp.tool()
async def search_chunks(
    query: str,
    k: int = 10,
    project_id: str | None = None,
    lambda_mult: float = 0.7,
) -> list[dict[str, Any]]:
    """Hybrid retrieval across the r3LAY knowledge base.

    Runs the three-stage pipeline: KNN (sqlite-vec) + BM25 (FTS5) + graph
    2-hop expansion, fused via RRF, deduped by cosine similarity, reranked
    with MMR for diversity.

    Args:
        query: Natural-language query string.
        k: Number of chunks to return (default 10).
        project_id: If set, scope to a single project. If None, searches
            across every project the current privacy level allows.
        lambda_mult: MMR diversity parameter in [0, 1]. 0.7 balances
            relevance and diversity; 1.0 = pure relevance, 0.0 = max
            diversity.

    Returns:
        List of {chunk_id, content, score, file_path, project_id, file_type,
        provenance, quality_weight}.
    """
    return await _post(
        "/search",
        {
            "query": query,
            "k": k,
            "project_id": project_id,
            "lambda_mult": lambda_mult,
        },
    )


@mcp.tool()
async def get_project_context(project_id: str) -> dict[str, Any]:
    """Load full context for a project — feeds /r3-plan session planning.

    Returns project metadata, the latest session notes (sn.md), active
    todos, open questions, 10 most recent decisions, and any pending
    conflicts. One call gives you everything /r3-plan needs to open a
    working session.

    Args:
        project_id: The project identifier (uuid or slug).

    Returns:
        {project, privacy, session_notes, active_todos, open_questions,
         recent_decisions, pending_conflicts}
    """
    return await _get(f"/project/{project_id}/context")


@mcp.tool()
async def list_active_projects() -> list[dict[str, Any]]:
    """Lightweight list of active projects with counts. READ-ONLY.

    Used by /r3-context — no LLM call, just DB queries. For projects with
    privacy=true or privacy=work, returns restricted fields only (name,
    type, counts — no content), so surfacing this response is safe across
    privacy levels.
    """
    return await _get("/projects/active")


@mcp.tool()
async def init_project(
    path: str,
    auto_write: bool = False,
) -> dict[str, Any]:
    """Extrapolate .r3lay/project.yaml from a project's manifest files.

    Scans README.md, pyproject.toml, package.json, Cargo.toml, go.mod,
    and .git/config to guess project name, description, language, tags,
    and repo URL. Returns a preview by default so the agent can show the
    user what r3LAY would write.

    Use this when the user drops a new folder into the workspace and it
    doesn't have a `.r3lay/project.yaml` yet. ALWAYS preview first and
    show the user the extrapolated metadata before writing — set
    auto_write=True only after explicit user confirmation.

    Args:
        path: Absolute path to the project directory.
        auto_write: If False (default), returns a preview of the metadata
            without writing. If True, creates .r3lay/project.yaml.

    Returns:
        {status: "preview"|"written"|"already_initialized", path, metadata}
    """
    body: dict[str, Any] = {"path": path, "auto_write": auto_write}
    return await _post("/project/init", body)


@mcp.tool()
async def compile_project(
    project_id: str,
    write: bool = True,
) -> dict[str, Any]:
    """Compile a project's knowledge into a single context document.

    Deterministic Karpathy-style synthesis — NO LLM call. Assembles project
    metadata, session notes (sn.md), active decisions, todos, open questions,
    pending conflicts, and file inventory into one structured markdown document
    that gives complete project context in a single read.

    Use this when:
    - Starting a new session and need full project context fast
    - The user asks for a "state of the project" summary
    - Cold-starting an agent that needs project context without multi-call
      assembly (load compiled.md instead of calling 5 separate endpoints)

    The compiled document is a SNAPSHOT — it reflects the state at compilation
    time. Re-compile after significant changes (new decisions, completed todos,
    session debrief) to keep it fresh.

    Args:
        project_id: The project to compile.
        write: If True (default), persists the document to .r3lay/compiled.md
            for cold-start loading. If False, returns the document without
            writing to disk.

    Returns:
        {status: "compiled", project_id, document, written_to,
         files, chunks, decisions, todos, questions, conflicts}
    """
    return await _post("/compile", {"project_id": project_id, "write": write})


@mcp.tool()
async def watcher_health() -> dict[str, Any]:
    """Check if the r3LAY file watcher is alive. READ-ONLY.

    The watcher writes a heartbeat on every activity (index, ingest drop,
    auto-init). This tool reads it and reports whether the watcher is
    considered alive (heartbeat < 5 minutes old).

    Call this at session start. If alive=false, warn the user that
    auto-indexing and _ingest/ processing are likely down — suggest
    running `r3lay-watch` or checking the tmux session.

    Returns:
        {alive, last_heartbeat, age_seconds, message?}
    """
    return await _get("/health/watcher")


@mcp.tool()
async def cross_references(project_id: str) -> list[dict[str, Any]]:
    """Find cross-project references for a project. READ-ONLY.

    Uses FTS5 to search the project's top active decisions against
    ALL other projects' indexed content. Returns matches grouped by
    project. Lightweight — pure SQL, no embedding calls, milliseconds.

    Use this when:
    - The user asks "is this related to anything else?"
    - Starting a planning session and want broader context
    - A decision or todo seems like it might overlap with another project

    Do NOT call this on every session start — it's a targeted tool for
    when cross-project awareness would add value.

    Args:
        project_id: The project to find cross-references for.

    Returns:
        List of {project_id, project_name, references: [{chunk_id,
        file_path, snippet, matched_decision}]}
    """
    return await _get(f"/projects/cross-references?project_id={project_id}")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────


def main() -> None:
    """Run the r3LAY MCP server over stdio.

    Called by Hermes as a subprocess (see mcp_servers.r3lay in
    config.template.yaml). Logs go to stderr — stdout is the MCP stdio
    transport and must not be polluted.
    """
    logging.basicConfig(
        level=os.environ.get("R3LAY_MCP_LOG_LEVEL", "WARNING"),
        stream=sys.stderr,
        format="%(asctime)s %(levelname)s r3lay.mcp %(message)s",
    )
    if not _load_api_key():
        logger.warning(
            "R3LAY_API_KEY not set and %s unreadable — bridge calls will 401. "
            "Start the bridge once (r3 up) to generate the secret, then restart "
            "the MCP server (Hermes will relaunch the stdio subprocess).",
            _SECRET_PATH,
        )
    mcp.run()


if __name__ == "__main__":
    main()
